=== infsci2560sp16/full-stack-web-project-QiangLiIS/src/main/resources/public/Tesa/WebContent/customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="customer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LastName" type="xs:string" />
							<xs:element name="FirstName" type="xs:string" />
							<xs:element name="SSN" type="xs:string" />
							<xs:element name="Gender" type="xs:string" />
							<xs:element name="DOB" type="xs:string" />
							<xs:element name="Age" type="xs:integer" />
							<xs:element name="Phone" type="xs:string" />
							<xs:element name="City" type="xs:string" />
							<xs:element name="State" type="xs:string" />
							<xs:element name="Zipcode" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== infsci2560sp16/full-stack-web-project-QiangLiIS/src/main/resources/public/Tesa/WebContent/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="customer.xsd">
	<person>
		<LastName>Li</LastName>
		<FirstName>Xia</FirstName>
		<SSN>123456789</SSN>
		<Gender>male</Gender>
		<DOB>3/21/92</DOB>
		<Age>24</Age>
		<Phone>412-6436-4654</Phone>
		<City>pittsburgh</City>
		<State>PA</State>
		<Zipcode>15232</Zipcode>
	</person>
	<person>
		<LastName>Zhang</LastName>
		<FirstName>Xiao</FirstName>
		<SSN>123456790</SSN>
		<Gender>male</Gender>
		<DOB>4/13/91</DOB>
		<Age>25</Age>
		<Phone>412-5436-4655</Phone>
		<City>pittsburgh</City>
		<State>PA</State>
		<Zipcode>15331</Zipcode>
	</person>
	<person>
		<LastName>Wang</LastName>
		<FirstName>Miao</FirstName>
		<SSN>123456791</SSN>
		<Gender>male</Gender>
		<DOB>8/1/92</DOB>
		<Age>24</Age>
		<Phone>412-5436-4656</Phone>
		<City>pittsburgh</City>
		<State>PA</State>
		<Zipcode>25230</Zipcode>
	</person>
	<person>
		<LastName>Pan</LastName>
		<FirstName>Wei</FirstName>
		<SSN>123456792</SSN>
		<Gender>female</Gender>
		<DOB>5/12/93</DOB>
		<Age>23</Age>
		<Phone>412-5436-4657</Phone>
		<City>pittsburgh</City>
		<State>PA</State>
		<Zipcode>15232</Zipcode>
	</person>
	<person>
		<LastName>Liu</LastName>
		<FirstName>Jing</FirstName>
		<SSN>123456793</SSN>
		<Gender>female</Gender>
		<DOB>7/15/91</DOB>
		<Age>25</Age>
		<Phone>412-5436-4658</Phone>
		<City>pittsburgh</City>
		<State>PA</State>
		<Zipcode>15321</Zipcode>
	</person>
</customer>
